### ISSUE TITLE
Fullstack Proposal Checklist

### ISSUE THREAD

**Issue by minucos** [espinalk212/ViewFlix#1]
Hi Kevin

Below is a checklist for you to use when putting together your project proposal this week.

We will meet on thursday or friday this week to go over your proposal, discuss a plan for next week, and make any tweaks.

I will be reviewing and checking off this list this morning, so please review any changes suggested tonight.

# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments
Looks great!
---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
Looking nice mate! Just a couple things to add:

- Need to add 2 x more bullet points to each MVP
- Number your MVPs (they are in the correct order already so just add those to the start of each MVP)
- Add time estimates (we can talk about these when we meet)
---

# Database Schema

- [ ] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [ ] indexed
    - [x] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [ ] Correctly formatted
    - [x] schema is written in a table format
    - [ ] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
Again nicely done. Only a few minor changes:

- Add an index to the ratings and genre columns for your video table. You'll likely want to look things up by these 2 columns
- Change UserVideos to be a Watchlist or Playlist, and add an order column
- Add in your associations for each model e.g. users should have_many playlists and videos
- minor formatting problems. Change Table names to lowercase, and remove the linebreaks between the Table name and the table itself
---

# Sample State

- [ ] State shape is flat!
- [ ] State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [ ] Top level slices
        - [ ] `entities`
        - [ ] `session`
        - [ ] `errors` (here or in `ui`)
        - [ ] `ui` (if needed)
    - [ ] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

---

# Backend Routes

- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

---

# Frontend Routes

- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

## Comments

**Comment by minucos** [comment]
Looking good mate!

I've added some comments to your MVP and schema for your review
